version: '3'

services:

  sentinel0:
    build: .
    image: opencbdc-tx
    tty: true
    restart: always
    command: ./build/src/uhs/twophase/sentinel_2pc/sentineld-2pc 2pc-compose.cfg 0
    ports:
      - 5555:5555
    depends_on:
      - "shard00"
      - "shard01"
      - "shard02"
      - "shard03"
      - "shard04"
      - "coordinator00"
    networks:
      - 2pc-network
    healthcheck:
      test: ["CMD-SHELL", "netstat -ltn | grep -c 5555"]
      interval: 30s
      timeout: 10s
      retries: 5

  coordinator00:
    build: .
    image: opencbdc-tx
    tty: true
    command: ./build/src/uhs/twophase/coordinator/coordinatord 2pc-compose.cfg 0 0
    expose: 
      - "1111"
    depends_on:
      - "shard00"
    networks:
      - 2pc-network
    healthcheck:
      test: ["CMD-SHELL", "netstat -ltn | grep -c 1111"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  #coordinator01:
  #  build: .
  #  image: opencbdc-tx
  #  tty: true
  #  command: ./build/src/uhs/twophase/coordinator/coordinatord 2pc-compose.cfg 0 1
  #  expose:
  #    - "2222"
  #  depends_on:
  #    - "shard00"
  #  networks:
  #    - 2pc-network
  #  healthcheck:
  #    test: ["CMD-SHELL", "netstat -ltn | grep -c 2222"]
  #    interval: 30s
  #    timeout: 10s
  #    retries: 5
  #  restart: always

#  coordinator02:
#    build: .
#    image: opencbdc-tx
#    tty: true
#    command: ./build/src/uhs/twophase/coordinator/coordinatord 2pc-compose.cfg 0 2
#    expose:
#      - "3333"
#    depends_on:
#      - "shard00"
#    networks:
#      - 2pc-network
#    healthcheck:
#      test: ["CMD-SHELL", "netstat -ltn | grep -c 3333"]
#      interval: 30s
#      timeout: 10s
#      retries: 5
#    restart: always
#  coordinator03:
#    build: .
#    image: opencbdc-tx
#    tty: true
#    command: ./build/src/uhs/twophase/coordinator/coordinatord 2pc-compose.cfg 0 3
#    expose:
#      - "4444"
#    depends_on:
#      - "shard00"
#    ports:
#      - 4747:4747
#    networks:
#      - 2pc-network
#    healthcheck:
#      test: ["CMD-SHELL", "netstat -ltn | grep -c 4444"]
#      interval: 30s
#      timeout: 10s
#      retries: 5
#    restart: always
  shard00:
    build: .
    image: opencbdc-tx
    tty: true
    command: ./build/src/uhs/twophase/locking_shard/locking-shardd 2pc-compose.cfg 0 0
    expose:
      - "6666"
    ports:
      - 6767:6767
    networks:
      - 2pc-network
    healthcheck:
      test: ["CMD-SHELL", "netstat -ltn | grep -c 6666"]
      interval: 30s
      timeout: 10s
      retries: 5
  shard01:
    build: .
    image: opencbdc-tx
    tty: true
    command: ./build/src/uhs/twophase/locking_shard/locking-shardd 2pc-compose.cfg 0 1
    expose:
      - "6777"
    ports:
      - 7777:7777
    networks:
      - 2pc-network
    healthcheck:
      test: ["CMD-SHELL", "netstat -ltn | grep -c 6777"]
      interval: 30s
      timeout: 10s
      retries: 5
  shard02:
    build: .
    image: opencbdc-tx
    tty: true
    command: ./build/src/uhs/twophase/locking_shard/locking-shardd 2pc-compose.cfg 0 2
    expose:
      - "6888"
    ports:
      - 8787:8787
    networks:
      - 2pc-network
    healthcheck:
      test: ["CMD-SHELL", "netstat -ltn | grep -c 6888"]
      interval: 30s
      timeout: 10s
      retries: 5
#  shard03:
#    build: .
#    image: opencbdc-tx
#    tty: true
#    command: ./build/src/uhs/twophase/locking_shard/locking-shardd 2pc-compose.cfg 0 3
#    expose:
#      - "7888"
#    ports:
#      - 1111:1111
#    networks:
#      - 2pc-network
#    healthcheck:
#      test: ["CMD-SHELL", "netstat -ltn | grep -c 6888"]
#      interval: 30s
#      timeout: 10s
#      retries: 5
#  shard04:
#    build: .
#    image: opencbdc-tx
#    tty: true
#    command: ./build/src/uhs/twophase/locking_shard/locking-shardd 2pc-compose.cfg 0 4
#    expose:
#      - "8888"
#    ports:
#      - 9999:9999
#    networks:
#      - 2pc-network
#    healthcheck:
#      test: ["CMD-SHELL", "netstat -ltn | grep -c 6888"]
#      interval: 30s
#      timeout: 10s
#      retries: 5

networks:
  2pc-network:
    name: 2pc-network
