version: '3'

services:

  sentinel0:
    build: .
    image: opencbdc-tx
    tty: true
    restart: always
    command: ./build/src/uhs/twophase/sentinel_2pc/sentineld-2pc 2pc-compose.cfg 0
    ports:
      - 5555:5555
    depends_on:
      - "coordinator0"
      - "shard0"
    networks:
      - 2pc-network
    healthcheck:
      test: ["CMD-SHELL", "netstat -ltn | grep -c 5555"]
      interval: 30s
      timeout: 10s
      retries: 5

  coordinator0:
    build: .
    image: opencbdc-tx
    tty: true
    command: ./build/src/uhs/twophase/coordinator/coordinatord 2pc-compose.cfg 0 0
    expose:
      - "7777"
    depends_on:
      - "shard0"
    networks:
      - 2pc-network
    healthcheck:
      test: ["CMD-SHELL", "netstat -ltn | grep -c 7777"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
  shard00:
    build: .
    depends_on:
      - shard01
      - shard02
    image: opencbdc-tx
    tty: true
    command: ./build/src/uhs/twophase/locking_shard/locking-shardd 2pc-compose.cfg 0 0
    expose:
      - "6666"
    ports:
      - 6767:6767
    networks:
      - 2pc-network
    healthcheck:
      test: ["CMD-SHELL", "netstat -ltn | grep -c 6666"]
      interval: 30s
      timeout: 10s
      retries: 5
  shard01:
    build: .
    image: opencbdc-tx
    tty: true
    command: ./build/src/uhs/twophase/locking_shard/locking-shardd 2pc-compose.cfg 0 1
    expose:
      - "6777"
    ports:
      - 7777:7777
    networks:
      - 2pc-network
    healthcheck:
      test: ["CMD-SHELL", "netstat -ltn | grep -c 6777"]
      interval: 30s
      timeout: 10s
      retries: 5
  shard02:
    build: .
    image: opencbdc-tx
    tty: true
    command: ./build/src/uhs/twophase/locking_shard/locking-shardd 2pc-compose.cfg 0 2
    expose:
      - "6888"
    ports:
      - 8787:8787
    networks:
      - 2pc-network
    healthcheck:
      test: ["CMD-SHELL", "netstat -ltn | grep -c 6888"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - shard01

networks:
  2pc-network:
    name: 2pc-network
